### ISSUE TITLE
Elf Bonuses to THAC0

### ISSUE THREAD

**Issue by lsware94** [Gibberlings3/Skills-and-Abilities#15]
There appears to be a minor issue with the proficiencies mapped to the Elves THAC0 bonuses currently. The bonus is not applying to bows, longswords, and shortswords and are instead being applied to the polearm and missile weapons. Otherwise keep up the good work.

**Comment by morpheus562** [comment]
Thank you! I see it is caused by the old RACETHAC.2DA that is still applying bonuses to the old proficiency slot. I will get this corrected on my next release.

**Comment by morpheus562** [comment]
Released the update fixing this issue. Thank you for the report!
