### ISSUE TITLE
Spell Penetration proficiency not showing up in character creation

### ISSUE THREAD

**Issue by Lyvewyrez** [Gibberlings3/Skills-and-Abilities#39]
Hello,

Thank you heaps for the mods by the way!
Need to check if I've done it correctly, have installed everything best I can as per youtube tutorial, including only the elements that are highlighted in the weidu log, including the NWN style.

In game though, the Spell Penetration proficiency is not showing, even though all the others are. Eex is installed and I ran the game through infinity loader. 

Is there something I have missed that could explain why it doesn't show up, or a log that could help figure it out?

Any help is greatly appreciated, thanks!

Side note, is there an easy way I could modify the percentage of magic resistance bypassed easily?

**Comment by Lyvewyrez** [comment]
As a note, it doesn't look like the Eex required profs are showing up. I tried reinstalling Eex, then reinstalling Skill and Abilities, but they are still not showing.

**Comment by morpheus562** [comment]
Do you have EEex installed before my proficiency component? What is your weidu log for reference? What version of EEex are you running since the proficiency component will not run with older versions of EEex.

**Comment by Lyvewyrez** [comment]
EEex was part of the install. Since figured out I had it in the wrong location with respect to S&B, where EEex was installed after S&B. 
Have tried reinstalling just S&B using the exec. but nothing changed. Have also tried reinstalling EEex with exec. then S&B after it, again choosing to reinstall all relevant components.

My versions are v1.0 beta for S&B and EEex is v0.9.16-alpha.
I noticed during one of the installs, it said skipping some of the components during S&B installation because it couldn't find EEex, but in the latest self-install using the G3 exec, it didn't show any of that, so I assume it didn't skip anything. 

The problem with using the executables by themselves after the fact, my Weidu.log is showing things out of order now, even though S&B was my last install, weidu.log is showing Eex lower on the list.

`~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #710 // Add New HLAs for ALL Classes and Kits: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #720 // Update Existing HLAs: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #130 // Blade Kit Enhancements: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #150 // Add New Fighter Abilities: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #141 // Allow Fighter Multiclasses to Achieve Higher than Specialized (2 pips) in Weapons Proficiencies -> Allow Fighter Multiclasses to Achieve Master (3 pips) in Weapon Proficiencies: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #70 // Add New Monk Abilities: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #80 // Add New Paladin Abilities: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #100 // Allow Inquisitor Kit to Cast Divine Spells: v1.0-beta
// Recently Uninstalled: ~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #300 // Update Weapon Fighting Styles: v1.0-beta
// Recently Uninstalled: ~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #313 // Overhaul Proficiency System - Add New Proficiencies and Weapon Styles -> NWN2 Style Proficiency Progression: v1.0-beta
// Recently Uninstalled: ~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #400 // 2H Weapon Additional Strength Bonus: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #300 // Update Weapon Fighting Styles: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #313 // Overhaul Proficiency System - Add New Proficiencies and Weapon Styles -> NWN2 Style Proficiency Progression: v1.0-beta
~SKILLS-AND-ABILITIES/SKILLS-AND-ABILITIES.TP2~ #0 #400 // 2H Weapon Additional Strength Bonus: v1.0-beta
~IWDIFICATION\SETUP-IWDIFICATION.TP2~ #0 #150 // IWD Class Updates: Bard: Use IWD Spell Progression: v5
~IWDIFICATION\SETUP-IWDIFICATION.TP2~ #0 #70 // IWD Class Updates: Druid: Use IWD Shapeshifting and Ability Progression: v5
~IWDIFICATION\SETUP-IWDIFICATION.TP2~ #0 #71 // IWD Class Updates: Druid: Allow Elves to be Druids: v5
~IWDIFICATION\SETUP-IWDIFICATION.TP2~ #0 #160 // IWD Class Updates: Paladin: Use IWD Spell Progression: v5
~IWDIFICATION\SETUP-IWDIFICATION.TP2~ #0 #120 // IWD Class Updates: Thief: Evasion: v5
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #50 // Avatar Morphing Script: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #60 // Weapon Animation Tweaks: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #110 // Icon Improvements: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #130 // Force All Dialogue to Pause Game: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #140 // Fix Boo's Squeak: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #170 // Unique Icons [Lava] -> Only replace icons that aren't already unique: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #191 // Use Character Colors Instead of Item Colors -> For non-magical shields and helmets: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #200 // Remove Annoying Visual Effects from Equipped Items -> Remove blur effect: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2010 // Separate Resist Fire/Cold Icon into Separate Icons [Angel]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1010 // More Interjections: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1020 // Alter HP Triggers for NPC Wounded Dialogues: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1040 // Improved Athkatlan City Guard: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1050 // Gradual Drow Item Disintegration: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1060 // Breakable Iron Non-Magical Shields, Helms, and Armor: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1070 // Improved Multi-Player Kick-Out Dialogues: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1075 // Send BioWare NPCs to an Inn [DavidW/Zed Nocear]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1120 // Stores Sell Higher Stacks of Items: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1161 // Multiple Strongholds [Sabre, Baldurdash, Weimer] -> Keep class restrictions: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1180 // Female Edwina [Davide Carte, Wendy Yung, Weimer]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1220 // Allow Cromwell to Upgrade Watcher's Keep Items: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1230 // Allow Cespenar to Use Cromwell Recipes: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #1270 // Change Cloakwood Mine Chapter End Change Trigger to Non-TotSC Behavior [plainab]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2090 // Change Experience Point Cap -> Remove experience cap: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2140 // Expanded Dual-Class Options: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2151 // Wear Multiple Protection Items -> No restrictions: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2170 // Cast Spells from Scrolls (and Other Items) at Character Level: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2192 // Limit Ability of Storekeepers to Identify Items -> Hybrid of both methods: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2220 // Change Magically Created Weapons to Zero Weight: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2240 // Un-Nerfed THAC0 Table: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2281 // Alter Cleric Spell Progression Table -> PnP table: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2294 // Alter Druid Spell and Level Progression Tables -> Use cleric level progression changes with pnp druid/cleric spell table: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2312 // Add Save Penalties for Spells Cast by High-Level Casters -> Arcane and divine magic: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2340 // Remove Summoning Cap for Celestials [Ardanis/GeN1e]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2360 // Remove Racial Restrictions for Single-Classes: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2371 // Alter Dual-Class Restrictions -> Allow non-humans to dual-class: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2358 // Alter Multi-Class Restrictions -> Install options one and three (everyone can multi-class anything they can single-class): v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2420 // Loosen Equipment Restrictions for Cleric Multi- and Dual-Classes: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2430 // Change Equipment Restrictions for Druid Multi- and Dual-Classes -> Loosen equipment restrictions for druid multi- and dual-classes: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2440 // Everyone Gets Bonus APR from Specialization [subtledoctor]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2520 // Allow Mages to Use Bucklers and Thieves to Use Small Shields [Angel]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2540 // Speed Up de'Arnise Keep Stronghold Quests: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2999 // Max HP at Level One: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3000 // Higher HP on Level Up -> Maximum: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3008 // Allow HP Rolls Through Level 20 [Angel]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3010 // Maximum HP Creatures [the bigg] -> For all creatures in game: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3031 // Easy Spell Learning -> 100% learn spells and no maximum cap: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3040 // Make Bags of Holding Bottomless: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3050 // Remove Fatigue from Restoration Spells: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3070 // Change Effect of Reputation on Store Prices -> Low Reputation Store Discount [Sabre]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3083 // Increase Ammo Stack Size -> Stacks of 120: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3093 // Increase Jewelry, Gem, and Miscellaneous Item Stacks -> Stacks of 120: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3103 // Increase Potion Stacking -> Stacks of 120: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3113 // Increase Scroll Stacking -> Stacks of 120: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3121 // Happy Patch - Alter How Party NPCs Complain About Reputation -> NPCs can be angry about reputation but never leave [Salk]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3123 // NPCs Don't Fight: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3125 // Neutral Characters Make Happy Comments at Mid-Range Reputation [Luiz]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3170 // No Drow Avatars On Party In Underdark [Weimer]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3200 // Sellable Items [icelus]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3230 // Taerom Makes Additional Ankheg Armor [Icendoan/grogerson]: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3280 // Give Every Class/Kit Four Weapon Slots: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3320 // No Depreciation in Stores: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #3330 // Make Party Members Less Likely to Die Irreversibly: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4000 // Adjust Evil Joinable NPC Reaction Rolls: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4020 // ToB-Style NPCs: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4025 // Allow NPC Pairs to Separate: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4031 // Consistent Stats: Edwin -> Use BG2 values: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4041 // Consistent Stats: Jaheira -> Use BG2 values: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4050 // Change Jaheira to Neutral Good Alignment: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4061 // Consistent Stats: Minsc -> Use BG2 values: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4071 // Consistent Stats: Viconia -> Use BG2 values: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4100 // Change Korgan to Neutral Evil Alignment: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4150 // Move Boo Into Minsc's Pack: v16
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #4170 // Ensure Shar-Teel Doesn't Die in the Original Challenge: v16
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #100 // Restore innate infravision to Half-Orc characters: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #101 // Prevent skeletal and incorporeal undead from being affected by Illithids' Devour Brain attack: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #102 // Change Spiritual Hammer into a ranged force weapon: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #103 // Allow Dispel/Remove Magic to take down Globes of Invulnerability: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #110 // Magical arrows and bolts deal bonus damage equal to their enchantment level: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #120 // Restore innate disease immunity to Paladins: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #125 // Rangers' Animal Empathy improves with experience: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #130 // Additional racial traits for Dwarves: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #140 // Additional racial traits for Gnomes: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #160 // PnP Undead: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #180 // PnP Mephits: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #185 // PnP Fey creatures: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #186 // Revised Call Woodland Beings spell: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #190 // PnP Elementals: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #191 // Increase the Hit Dice of Elemental Princes: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #261 // Altered XP rewards from locks, traps and scrolls -> Improved (lowered) XP rewards from locks, traps and scrolls: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #310 // Distinctive creature coloring: v4.53
~ATWEAKS\SETUP-ATWEAKS.TP2~ #0 #315 // Distinctive creature soundsets: v4.53
~CDTWEAKS\SETUP-CDTWEAKS.TP2~ #0 #2060 // Weapon Styles for All: v16
~KLATU\SETUP-KLATU.TP2~ #0 #1020 // Prepared Wishes: 1.7
~KLATU\SETUP-KLATU.TP2~ #0 #1050 // Appropriate XP Rewards for Cowled Enforcers: 1.7
~KLATU\SETUP-KLATU.TP2~ #0 #2110 // Treat all Innate Abilities as Non-Magical (Unaffected by Wild/Dead Magic and Silence): 1.7
~KLATU\SETUP-KLATU.TP2~ #0 #2120 // Treat all Psionic Abilities as Non-Magical (Unaffected by Wild/Dead Magic and Silence): 1.7
~KLATU\SETUP-KLATU.TP2~ #0 #2130 // Treat all Bardsong Effects as Non-Magical (Unaffected by Wild/Dead Magic): 1.7
~MIH_TWEAKS\SETUP-MIH_TWEAKS.TP2~ #0 #2 // Spell Level affects Saving Throws: v2
~HQ_SOUNDCLIPS_BG2EE\HQ_SOUNDCLIPS_BG2EE.TP2~ #0 #0 // Install high quality soundclips for new BG2EE content: 1.2
~BGEECLASSICMOVIES\BGEECLASSICMOVIES.TP2~ #0 #0 // Restore BG1 movies to BG:EE -> Replace all movies: v2.3.1
~BGEECLASSICMOVIES\BGEECLASSICMOVIES.TP2~ #0 #3 // Restore BG1 Chapter and Dream Screens: v2.3.1
~FORGOTTEN-ARMAMENT\FORGOTTEN-ARMAMENT.TP2~ #0 #4 // Update Items Setting an Ability Score to Increment the Increase: v1.3
~EET_END\EET_END.TP2~ #0 #0 // EET end (last mod in install order) -> Standard installation
~PPE\SETUP-PPE.TP2~ #0 #0 // Portraits Portraits Everywhere (PPE) - core component: 1.02
~PPE\SETUP-PPE.TP2~ #0 #100 // Category Portraits (Recommended) -> Sequenced: 1.02
~PPE\SETUP-PPE.TP2~ #0 #10 // Isandir's CHARNAME Portraits: 1.02
~PPE\SETUP-PPE.TP2~ #0 #20 // Replace Low Quality TOB & SOA Portraits: 1.02
~PPE\SETUP-PPE.TP2~ #0 #25 // Edwin/Edwina: 1.02
~PPE\SETUP-PPE.TP2~ #0 #30 // Ust Natha Drow NPCs: 1.02
~EEEX/EEEX.TP2~ #0 #0 // EEex: v0.9.16-alpha
~EEEX/EEEX.TP2~ #0 #1 // Enable effect menu module - LShift-on-hover to view spells affecting creature: v0.9.16-alpha
~EEEX/EEEX.TP2~ #0 #2 // Enable timer module - Visual indicators for modal actions, contingencies, and spell/item cooldowns: v0.9.16-alpha
~EEEX/EEEX.TP2~ #0 #3 // Timer module - Show modal actions (red bar): v0.9.16-alpha
~EEEX/EEEX.TP2~ #0 #4 // Timer module - Show contingencies (green bar): v0.9.16-alpha
~EEEX/EEEX.TP2~ #0 #5 // Timer module - Show spell/item cooldowns (cyan bar): v0.9.16-alpha
~BUBB_SPELL_MENU_EXTENDED\BUBB_SPELL_MENU_EXTENDED.TP2~ #0 #0 // Bubb's Spell Menu Extended: v4.5.4
~BUBB_REVERT_PATHFINDING\BUBB_REVERT_PATHFINDING.TP2~ #0 #0 // Bubb's v2.6.6.0+ Pathfinding Revert: 1.1
~BGGOEET/SETUP-BGGOEET.TP2~ #0 #0 // Baldur's Gate Graphics Overhaul for EET -> Purple Patches: v2.0 beta
`

If you have any suggestions or need any logs etc, any help would be greatly appreciated. As an aside, had troubles originally getting PI to work, when I imported your Weidu.log and pressed install, it had some load order issues. Only way I could progress was setting up the left side of PI and try to put each element as best I could in the same order as your weidu.log had it. Worked for the most part, but there was errors during the install.

Is this salvagable or do I basically need to start again from a fresh install?

**Comment by morpheus562** [comment]
I'd recommend doing a fresh install at this point. EEex is showing as after Skills and Abilities, so that appears to be the reason why. Lots of mods have had updates since I last posted my logs, and I'm building out new ones.

**Comment by Lyvewyrez** [comment]
Just leaving a comment to say that a fresh install worked this time, the EEex specific items now show up. This is likely due to the original install order being wrong, which reinstalling the individual components did not fix.

As an aside, a number of mods wouldn't install or hard failed during install, even though I was following the install order list found here: https://github.com/morpheus562/Baldurs-Gate-Install-Order-List-Repository

These were Sirene, enhanced power gaming scripts, iwdification, might and guile as well as RR.

Thanks.
