### ISSUE TITLE
Bug and To Do list: Craft Scrolls

### ISSUE THREAD

**Issue by Grammarsalad** [Gibberlings3/Skills-and-Abilities#43]
# **Bugs**

- Divine scroll menu available to single class mages (though cannot create scrolls) (4)
- Unknown HLA issue (5)
- xp cost seems to be getting added when it shouldn't (by scrcrft.2da) (6)
~~- Craft Scroll not self renewing (1)~~
~~- Craft Scroll not being assigned to mage multiclass (or any mc) (2)~~
~~- Dialog block (that doesn't seem to work) requiring 100 xp even when requirements are less than that (3)~~
~~- craft scroll not getting added to non-kitted cleric (7)~~
~~- Dialog doesn't compile when special characters are in spl name (",~,%) (7)~~

# **To Do**
- Ensure creation only available if character can cast at least one of the relevant spell type (arcane vs divine) (bug 4)
- Figure out the hla issue (install with olvynspells) (bug 5)
- Make sure create scroll is implemented exactly as specified by scrcrft.2da (bug 6+)
- Exclude spls with empty spell names (it just should even though it probably doesn't matter)
- Make compatible with Olyvnspells, etc.
- Add possibility to create scrolls known rather than just those memorized
- - Apply the spl by clab by class, and then make the character immune to all applications
- Make the requirements more obvious when first using special ability (in special ability description and in dialogue text)
- Ensure that create scroll is added only once for mc and dual class
- - State in early in text exact costs for a given spell level when ability is activated
- - Let char know if they don't meet minimum requirements
- - upon creation, ensure that there is notification that x resource has been used up
~~- Get rid of characters in spell names that mess up dialog (tildas, quotes, percentage symbols) (bug 7)~~
~~- Make craft scroll spell self renewing (bug 1)~~
~~- Assign craft scroll to mc (Bug 2), priests (bug 7) and any other classes it should be added to~~
~~- Delete that weird xp dialog block (bug 3)~~

**Comment by morpheus562** [comment]
Component removed.
