### ISSUE TITLE
"Archer Updates" component not documented in the `readme`

### ISSUE THREAD

**Issue by Kallinteris-Andreas** [Gibberlings3/Skills-and-Abilities#52]
This mod has this component:
```yaml
  - index: 170
    component_name: 'Update Archer to provide to hit and damage bonuses per the kit description: v2.1'
```

but the README does not explain what it does, (also should it be used with a mod that revises the `archer` kit such as ArtisanKitpack or `A7's archer overhaul`)

Thanks!

**Comment by morpheus562** [comment]
The vanilla version of the Archer does not gain the +1 bonus to hit and damage as per the description for the kit. This ensures the Archer gains the bonuses in-line with the kit description. I would not recommend this with other Archer overhauls since this change the kit.
