### ISSUE TITLE
Aura of Despair Affecting Party when near a Dismissed Dorn

### ISSUE THREAD

**Issue by jgjensen** [Gibberlings3/Skills-and-Abilities#53]
I am not certain that this is a bug, and it does not have any significant impact on the game in any event, but I noticed after installing the new Paladin abilities component that if I dismiss Dorn and then get near him in the Friendly Arm Inn, his Aura of Despair affects my party members within the area of effect.  Given that combat near a dismissed NPC is unlikely to occur, this is not a big deal, but I thought I'd mention it as I doubt it is intended behavior.

**Comment by morpheus562** [comment]
Not really intended, but it makes sense. He's not part of the party any longer and it is meant to target non-party members.
